## Ans(2):

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler


### Step 1: Data Preparation

In [2]:
df = pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv')

### Basic statistics

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Gender                          2111 non-null   object 
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object 
 5   FAVC                            2111 non-null   object 
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object 
 9   SMOKE                           2111 non-null   object 
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object 
 12  FAF                             21

In [4]:
df

Gender        Age    Height      Weight family_history_with_overweight  \
0     Female  21.000000  1.620000   64.000000                            yes   
1     Female  21.000000  1.520000   56.000000                            yes   
2       Male  23.000000  1.800000   77.000000                            yes   
3       Male  27.000000  1.800000   87.000000                             no   
4       Male  22.000000  1.780000   89.800000                             no   
...      ...        ...       ...         ...                            ...   
2106  Female  20.976842  1.710730  131.408528                            yes   
2107  Female  21.982942  1.748584  133.742943                            yes   
2108  Female  22.524036  1.752206  133.689352                            yes   
2109  Female  24.361936  1.739450  133.346641                            yes   
2110  Female  23.664709  1.738836  133.472641                            yes   

     FAVC  FCVC  NCP       CAEC SMOKE      CH2O  SCC       FAF       TUE  \
0      no   2.0  3.0  Sometimes    no  2.000000   no  0.000000  1.000000   
1      no   3.0  3.0  Sometimes   yes  3.000000  yes  3.000000  0.000000   
2      no   2.0  3.0  Sometimes    no  2.000000   no  2.000000  1.000000   
3      no   3.0  3.0  Sometimes    no  2.000000   no  2.000000  0.000000   
4      no   2.0  1.0  Sometimes    no  2.000000   no  0.000000  0.000000   
...   ...   ...  ...        ...   ...       ...  ...       ...       ...   
2106  yes   3.0  3.0  Sometimes    no  1.728139   no  1.676269  0.906247   
2107  yes   3.0  3.0  Sometimes    no  2.005130   no  1.341390  0.599270   
2108  yes   3.0  3.0  Sometimes    no  2.054193   no  1.414209  0.646288   
2109  yes   3.0  3.0  Sometimes    no  2.852339   no  1.139107  0.586035   
2110  yes   3.0  3.0  Sometimes    no  2.863513   no  1.026452  0.714137   

            CALC                 MTRANS           NObeyesdad  
0             no  Public_Transportation        Normal_Weight  
1      Sometimes  Public_Transportation        Normal_Weight  
2     Frequently  Public_Transportation        Normal_Weight  
3     Frequently                Walking   Overweight_Level_I  
4      Sometimes  Public_Transportation  Overweight_Level_II  
...          ...                    ...                  ...  
2106   Sometimes  Public_Transportation     Obesity_Type_III  
2107   Sometimes  Public_Transportation     Obesity_Type_III  
2108   Sometimes  Public_Transportation     Obesity_Type_III  
2109   Sometimes  Public_Transportation     Obesity_Type_III  
2110   Sometimes  Public_Transportation     Obesity_Type_III  

[2111 rows x 17 columns]

### Data Cleaning

In [5]:
df.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [6]:
## Checking All Columns name present in dataset
df.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [7]:
df.shape

(2111, 17)

### Split the dataset into train and test sets

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df[['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS']], df['NObeyesdad'], test_size=0.25, random_state=42)

In [10]:
#Convert categorical variables to numerical representations
# In this case, we need to encode the 'NObeyesdad' column (target variable)
label_encoder = LabelEncoder()
y_train_encode = label_encoder.fit_transform(df['NObeyesdad'])
y_test_encode = label_encoder.transform(df['NObeyesdad'])

In [11]:
y_train_encode

array([1, 1, 1, ..., 4, 4, 4])

In [12]:
y_train_encode.shape

(2111,)

In [13]:
#Convert categorical variables to numerical representations
# In this case, we need to encode the feature column (input variable)

One_Hot_Encoder = OneHotEncoder(drop='first',sparse=False)
X_train_encode = One_Hot_Encoder.fit_transform(df[['Gender','family_history_with_overweight','FAVC','CAEC','SMOKE','SCC','CALC','MTRANS']])
X_test_encode = One_Hot_Encoder.transform(df[['Gender','family_history_with_overweight','FAVC','CAEC','SMOKE','SCC','CALC','MTRANS']])

In [14]:
X_train_encode

array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.]])

In [15]:
X_train_encode.shape

(2111, 15)

### Create four classification models

In [16]:
logreg = LogisticRegression()
svc = SVC()
dt = DecisionTreeClassifier()
rfc = RandomForestClassifier()

### Train the models

In [17]:
logreg.fit(X_train_encode, y_train_encode)

C:\Users\sudhir\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [18]:
svc.fit(X_train_encode, y_train_encode)

SVC()

In [19]:
dt.fit(X_train_encode, y_train_encode)

DecisionTreeClassifier()

In [20]:
rfc.fit(X_train_encode, y_train_encode)

RandomForestClassifier()

## Prediction

In [28]:
logreg_predictions = logreg.predict(X_test_encode)
logreg_predictions

array([6, 1, 6, ..., 4, 4, 4])

In [29]:
svc_predictions = svc.predict(X_test_encode)
svc_predictions

array([6, 1, 6, ..., 4, 4, 4])

In [30]:
dt_predictions = dt.predict(X_test_encode)
dt_predictions

array([6, 1, 1, ..., 4, 4, 4])

In [31]:
rfc_predictions = rfc.predict(X_test_encode)
rfc_predictions

array([6, 1, 1, ..., 4, 4, 4])

### Evaluate the models on the test set

In [21]:
logreg_accuracy = logreg.score(X_test_encode, y_test_encode)
svc_accuracy = svc.score(X_test_encode, y_test_encode)
dt_accuracy = dt.score(X_test_encode, y_test_encode)
rfc_accuracy = rfc.score(X_test_encode, y_test_encode)

### Print the accuracies of the models

In [22]:
print('Logistic Regression accuracy:', logreg_accuracy)
print('Support Vector Machine accuracy:', svc_accuracy)
print('Decision Tree accuracy:', dt_accuracy)
print('Random Forest accuracy:', rfc_accuracy)

Logistic Regression accuracy: 0.541923259118901
Support Vector Machine accuracy: 0.6215063950734249
Decision Tree accuracy: 0.6527711984841308
Random Forest accuracy: 0.6527711984841308


## 2nd_Method

In [25]:
# Step 4: Model Training and Evaluation
# Choose four different classification algorithms
from sklearn.metrics import classification_report, accuracy_score
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    SVC(),
    RandomForestClassifier()
]

for classifier in classifiers:
    # Fit the classifier to the training data
    classifier.fit(X_train_encode, y_train_encode)
    
    # Make predictions on the test set
    y_pred = classifier.predict(X_test_encode)
    
    # Evaluate the model
    accuracy = accuracy_score(y_test_encode, y_pred)
    report = classification_report(y_test_encode, y_pred)
    
    # Print the results
    print(f"Classifier: {classifier.__class__.__name__}")
    print(f"Accuracy: {accuracy}")
    print(f"Classification Report:\n{report}")
    print("-----------------------------------------")


Classifier: DecisionTreeClassifier
Accuracy: 0.6527711984841308
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.83      0.75       272
           1       0.80      0.65      0.72       287
           2       0.56      0.57      0.57       351
           3       0.42      0.74      0.54       297
           4       0.82      0.99      0.90       324
           5       0.85      0.39      0.54       290
           6       0.79      0.37      0.51       290

    accuracy                           0.65      2111
   macro avg       0.70      0.65      0.64      2111
weighted avg       0.70      0.65      0.64      2111

-----------------------------------------
Classifier: RandomForestClassifier
Accuracy: 0.6527711984841308
Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.82      0.74       272
           1       0.82      0.64      0.72       287
           2       0.56 